
import React from 'react';
import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>AI Generated App</title>
        <meta name="description" content="Professional Next.js app generated by AI" />
      </Head>
      <main className="min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100">
        <div className="container mx-auto px-4 py-16">
          <h1 className="text-4xl font-bold text-center text-gray-800 mb-8">
            Welcome to AI Generated App
          </h1>
          <p className="text-lg text-center text-gray-600 max-w-2xl mx-auto">
            This is a professional Next.js application deployed through our enhanced workflow: 
            Claude → GitHub → Render with build cache optimization.
          </p>
        </div>
      </main>
    </div>
  );
}
            